apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  type: {{ .Values.service.type }}
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: {{ .Values.service.backendPort }}
    targetPort: {{ .Values.service.backendPort }}
