apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: {{ .Values.service.frontendPort }}
    targetPort: {{ .Values.service.frontendPort }}
