replicaCount: 2

image:
  repository: akslabacr1204.azurecr.io
  frontendTag: "frontend:v1"
  backendTag: "backend:v1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  frontendPort: 80
  backendPort: 5000

ingress:
  enabled: true
  host: "" # 如果没有域名，可留空，使用 IP 地址
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

resources: {}
